behaviors:
  BallAgent:
    trainer_type: sac
    hyperparameters:
      batch_size: 64
      buffer_size: 150000
      learning_rate: 0.0003
      buffer_init_steps: 10000
      init_entcoef: 0.1
      steps_per_update: 12
      init_entcoef: 1.0
      learning_rate_schedule: constant
    network_settings:
      normalize: true
      hidden_units: 64
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 3
    max_steps: 50000000
    time_horizon: 1000
    summary_freq: 50000
    