behaviors:
  Suika:
    trainer_type: sac
    hyperparameters:
      batch_size: 256
      buffer_size: 5000000
      learning_rate: 0.001
      buffer_init_steps: 10000
      init_entcoef: 1.0
      steps_per_update: 12
      tau: 0.005
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 250
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 5000000
    time_horizon: 5000
    summary_freq: 30000
