behaviors:
  Suika:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 4000
      learning_rate: 0.001
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 500
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 50000000
    time_horizon: 500
    summary_freq: 5000
